### ISSUE TITLE
Tech Meeting Task List

### ISSUE THREAD

**Issue by maryfries** [bjc-edc/bjc-r#18]
Thanks for a great meeting! Here are our tasks:

-  [x] @brianharvey to post a notice to bjc.berkeley.edu/bjc-r saying that "This site will soon be replaced by the contents of bjc.edc.org. You can continue to access the contents that are currently on this site at http://beautyjoy.github.io/bjc-r/."

- [x]  @cycomachead to resolve [JSON security vulnerabilities](https://github.com/bjc-edc/bjc-r/network/dependencies)

- [x] Mary to talk with June about mirror and long term BJC storage plan (having bjc.edc.org redirect to mirror, which will become permanent site; use JS to keep path same during redirect)

- [x] Mary to talk with June about plan for exposed solutions on github.io (moving them to XML files in an embedded private repo)

- [x] @brianharvey to set up mirror on bjc.berkeley.edu/bjc-r _after_ getting OK from Mary and June

- [x] Mary to schedule Dec 2017 meeting to address exposed solutions

- [x] Mary to schedule Jan 2018 meeting to set up mirror and post to Piazza
